# Generated by Django 5.2.17 on 2026-10-05 12:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('setor', models.CharField(blank=True, help_text='Ex.: Diretoria comercial', max_length=80, verbose_name='Setor / cargo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, help_text='Inativos não aparecem em novos agendamentos.', verbose_name='Ativo')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da viagem')),
                ('horario_previsto', models.TimeField(verbose_name='Horário previsto')),
                ('origem', models.CharField(help_text='Cidade/UF ou aeródromo. Ex.: Balsas – MA (SNBS)', max_length=80, verbose_name='Origem')),
                ('destino', models.CharField(help_text='Cidade/UF ou aeródromo. Ex.: Palmas – TO (SBPJ)', max_length=80, verbose_name='Destino')),
                ('finalidade', models.CharField(choices=[('visita_filial', 'Visita a filial'), ('reuniao_cliente', 'Reunião com cliente'), ('treinamento', 'Treinamento de colaboradores'), ('evento', 'Participação em evento'), ('visita_tecnica', 'Visita técnica'), ('acompanhamento', 'Acompanhamento de operação'), ('reuniao_adm', 'Reunião administrativa'), ('outra', 'Outra (detalhar na descrição)')], max_length=30, verbose_name='Finalidade do voo')),
                ('descricao', models.TextField(help_text='Explique o motivo do deslocamento. Ex.: Reunião de fechamento de safra com o cliente X.', verbose_name='Descrição da viagem')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=10, verbose_name='Situação')),
                ('horas_voo', models.DecimalField(blank=True, decimal_places=1, help_text='Em horas decimais. Ex.: 1,5 = 1h30', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Horas de voo')),
                ('combustivel_consumido', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Combustível consumido (L)')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=200, verbose_name='Motivo do cancelamento')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frota.aeronave')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('passageiros', models.ManyToManyField(related_name='viagens', to='viagens.passageiro', verbose_name='Passageiros')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo agendamento')),
            ],
            options={
                'verbose_name': 'viagem',
                'verbose_name_plural': 'viagens',
                'ordering': ['-data', '-horario_previsto'],
            },
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('taxas', 'Taxas aeroportuárias'), ('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('manutencao', 'Manutenção relacionada ao voo'), ('outros', 'Outros custos')], max_length=20, verbose_name='Tipo de custo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor (R$)')),
                ('descricao', models.CharField(help_text='Ex.: Taxa de pouso em Palmas', max_length=200, verbose_name='Descrição')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da despesa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='viagens.viagem')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('quantidade_litros', models.DecimalField(decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Quantidade abastecida (L)')),
                ('tipo_combustivel', models.CharField(choices=[('qav1', 'QAV-1 (querosene de aviação)'), ('avgas', 'AVGAS 100LL (gasolina de aviação)')], max_length=10, verbose_name='Tipo de combustível')),
                ('valor_litro', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Valor por litro (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Valor total (R$)')),
                ('local', models.CharField(help_text='Ex.: Aeroporto de Balsas (SNBS)', max_length=80, verbose_name='Local do abastecimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='frota.aeronave')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('viagem', models.ForeignKey(blank=True, help_text='Opcional. Deixe em branco para abastecimentos fora de viagem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='viagens.viagem', verbose_name='Viagem relacionada')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='viagem',
            index=models.Index(fields=['status', 'data'], name='viagens_via_status_f92c59_idx'),
        ),
    ]
