# Generated by Django 5.2.17 on 2026-10-05 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Nome usado internamente. Ex.: King Air da diretoria.', max_length=60, verbose_name='Identificação')),
                ('fabricante', models.CharField(blank=True, max_length=60, verbose_name='Fabricante')),
                ('modelo', models.CharField(max_length=60, verbose_name='Modelo')),
                ('prefixo', models.CharField(help_text='Ex.: PR-LVN', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}-[A-Z]{3}$', 'Use o formato de matrícula brasileira: duas letras, hífen e três letras (ex.: PR-LVN).')], verbose_name='Prefixo (matrícula)')),
                ('capacidade_passageiros', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade de passageiros')),
                ('ativa', models.BooleanField(default=True, verbose_name='Em operação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'aeronave',
                'verbose_name_plural': 'aeronaves',
                'ordering': ['-ativa', 'prefixo'],
            },
        ),
    ]
